# # whether print configs
# print_configs = false

# # collect interval, default 15s
# interval_seconds = 15

# # whether collect protocol stats on Linux
# collect_protocol_stats = false

# # setting interfaces will tell categraf to gather these explicit interfaces
# interfaces = ["eth0"]