# # collect interval
interval = 3

[[instances]]
address = "127.0.0.1:3306"
username = "root"
password = "1234"

# # set tls=custom is enable tls
# parameters = "tls=false"

extra_status_metrics = true
extra_innodb_metrics = false

# # timeout
# timeout_seconds = 3

# # interval = global.interval * interval_times
# interval_times = 1

# important! use global unique string to specify instance
labels = { instance="n9e-10.2.3.4:3306" }

## Optional TLS Config
# use_tls = false
# tls_min_version = "1.2"
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
# insecure_skip_verify = true