# # print configurations
# PrintConfigs = false

# # collect interval
# IntervalSeconds = 15

# # append labels for series
# Labels = { key1 = "value1", key2 = "value2" }

# [[Targets]]
# # redis server address
# Address = "127.0.0.1:6379"

# # redis server password
# Password = ""

# # collect interval this target
# IntervalSeconds = 15
