# # whether print configs
# print_configs = false

# # collect interval
# interval = 15

# [[instances]]
# # redis server address
# address = "127.0.0.1:6379"

# # redis server password
# password = ""

# # collect interval for this instance
# interval = 15

# # append labels for this instance
# labels = { instnace = "10.23.4.4:6379" }
