[Global]
# whether print configs
PrintConfig = false
# add label(agent_hostname) to series
Hostname = ""
# will not add label(agent_hostname) if true
OmitHostname = false

[Global.Labels]
region = "shanghai"
env = "localhost"

[WriterOpt]
# default: 2000
Batch = 2000

[[Writers]]
Url = "http://127.0.0.1:19000/prometheus/v1/write"
# Basic auth username
BasicAuthUser = ""
# Basic auth password
BasicAuthPass = ""
# timeout settings, unit: ms
Timeout = 3000
DialTimeout = 3000
TLSHandshakeTimeout = 3000
ExpectContinueTimeout = 1000
IdleConnTimeout = 90000
# time duration, unit: ms
KeepAlive = 30000
MaxConnsPerHost = 0
MaxIdleConns = 100
MaxIdleConnsPerHost = 100