[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
hostname = ""

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval_seconds = 15

# [global.labels]
# region = "shanghai"
# env = "localhost"

[writer_opt]
# default: 2000
batch = 2000

[[writers]]
url = "http://127.0.0.1:19000/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

# timeout settings, unit: ms
timeout = 3000
dial_timeout = 3000
tls_handshake_timeout = 3000
expect_continue_timeout = 1000
idle_conn_timeout = 90000

# time duration, unit: ms
keep_alive = 30000
max_conns_per_host = 0
max_idle_conns = 100
max_idle_conns_per_host = 100
