[prometheus]
  enable=true
  scrape_config_file="/path/to/scrape.yaml"
  web_address="127.0.0.1:9091"
  ##wal file storage path ,default ./data-agent
  # wal_storage_path="/path/to/storage"
  ##wal reserve time duration, default value is 2 hour
  # wal_min_duration=2

