[prometheus]
  enable=true
  scrape_config_file="/path/to/in_cluster_scrape.yaml"
  ##wal file storage path ,default ./data-agent
  # wal_storage_path="/path/to/storage"
  ##wal reserve time duration, default value is 2 hour
  # wal_min_duration=2

