# # collect interval
# interval = 15

############################################################################
# !!! uncomment [[instances]] to enable this plugin
[[instances]]
# # interval = global.interval * interval_times
# interval_times = 1

# append some labels to metrics
labels = { cluster="cloud-n9e-kafka" }
kafka_uris = ["127.0.0.1:9092","127.0.0.1:9092","127.0.0.1:9092"]