[[instances]]
metrics_name_prefix = "kafka_"
  
metrics_drop = [
  "*_EventType",
  "*_MeanRate",
  "*_RateUnit",
  "*_LatencyUnit",
  "*_75thPercentile",
  "*_95thPercentile",
  "*_98thPercentile",
  "*_999thPercentile",
  "*_Min",
  "*_Max",
  "*_StdDev"
]
  
urls = ["http://localhost:8090/jolokia"]

  [[instances.metric]]
    name         = "controller"
    mbean        = "kafka.controller:name=*,type=*"
    field_prefix = "$1_"

  [[instances.metric]]
    name         = "replica_manager"
    mbean        = "kafka.server:name=*,type=ReplicaManager"
    field_prefix = "$1_"

  [[instances.metric]]
    name         = "purgatory"
    mbean        = "kafka.server:delayedOperation=*,name=*,type=DelayedOperationPurgatory"
    field_prefix = "$1_"
    field_name   = "$2"

  [[instances.metric]]
    name         = "zookeeper"
    mbean        = "kafka.server:name=*,type=SessionExpireListener"
    field_prefix = "$1_"

  [[instances.metric]]
    name     = "user"
    mbean    = "kafka.server:user=*,type=Request"
    field_prefix = ""
    tag_keys = ["user"]

  [[instances.metric]]
    name         = "request"
    mbean        = "kafka.network:name=*,request=*,type=RequestMetrics"
    field_prefix = "$1_"
    tag_keys     = ["request"]

  [[instances.metric]]
    name         = "topics"
    mbean        = "kafka.server:name=*,type=BrokerTopicMetrics"
    field_prefix = "$1_"

  [[instances.metric]]
    name         = "topic"
    mbean        = "kafka.server:name=*,topic=*,type=BrokerTopicMetrics"
    field_prefix = "$1_"
    tag_keys     = ["topic"]

  [[instances.metric]]
    name       = "partition"
    mbean      = "kafka.log:name=*,partition=*,topic=*,type=Log"
    field_name = "$1"
    tag_keys   = ["topic", "partition"]

  [[instances.metric]]
    name       = "partition"
    mbean      = "kafka.cluster:name=UnderReplicated,partition=*,topic=*,type=Partition"
    field_name = "UnderReplicatedPartitions"
    tag_keys   = ["topic", "partition"]
